code_version: "2out v Nov 12 2025 16:33:06"
cxode_version: "2out v Dec  3 2025 13:58:12"

# Trigger 1 Settings
trigger_1_test: 1
chance_to_test_trigger_1: 100.0
number_of_trigger_1_attempts: 1.0
seconds_to_wait_for_restart: 8.0

# Update Database
update_db: 1

# Set max watt and load time for load test. Can be done within loads as well.
# maxw: 713
hold_load_time: 0 # How long the load will stay on when enabled, can be set outside the loads list to affect all loads.

# Loads Test
loads:
  toggle: 1
  test_steps:
  - { cccv: 0, cuv: 0, maxw: 713, CV: 40, dim: 100, power: 60, } # Set max watt on the first load, so it doesn't need to be set later.
  - { cccv: 0, CV: 40, dim: 0, below_power: 0.05, time_before_load_on: 3.0 }
  - { cccv: 1, cuv: 12, CC: 3.3, dim: 100, power: 36.0 }
  - { cccv: 2, cuv: 24, CC: 2.5, dim: 100, power: 56.0 }
  - { cccv: 3, cuv: 36, CC: 2.0, dim: 100, power: 66.0 }
  - { cccv: 4, cuv: 48, CC: 1.5, dim: 100, power: 66.0 }
  - { cccv: 4, CC: 1.5, dim: 0, below_power: 0.05, time_before_load_on: 3.0 }
  - { toggle: 1, cccv: 255, cuv: 0, dim: 100}      # Set cv 255 in advance to avoid future delays

sensor1: 1
pdline: 1

rs485: 1

commission:
  toggle: 1
  settings:
    "/actuators/ALL":
      cccv: "255"
      cuv: "0"
      maxw: "100"
      pp: 100

append_to_file: 1