{
  "subnet": "192.168.2.255",      # Searches through this set of IPs (e.g. 192.168.3.255 will search 192.168.3.abc - 192.168.3.255)
  "scan_start": 11,               # Host ID of an IP address to start scanning from. For example, a value of 11 will mean that it starts scanning from 192.168.2.11
  "scan_end": 255,                # Host ID of an IP address to stop scanning from. 255 is the highest value this can be set to. 

  "Load Machine COM": "COM4",     # Can be an integer or a string 
  "Microcontroller COM": "COM3",  # Does nothing currently, need to test this and above one

  "prompt_continue_key": 'DOWN',  # Need to set this for each send_test_prompt that uses it
  "prompt_end_test_key": 'enter'  # Does nothing currently
  
}