cxode_version: "super v Mar  9 2026 17:05:33"

# Trigger 1 Settings
trigger_1_test: 1
chance_to_test_trigger_1: 10.0
number_of_trigger_1_attempts: 1.0
seconds_to_wait_for_restart: 8.0

# Update Database
update_db: 1

# Set max watt and load time for load test.
maxw: 713
time_before_load: 0.75
hold_load_time: 1

# Loads Test
loads:
  toggle: 1
  time_before_load_on: 0

  dim: 100
  test_steps:
    - { cccv: 0, Load_CV: 37.0, power: 45.0 }    # Ideal Load_CV: 40, was 39,38
    - { cccv: 1, Load_CC: 4.7, power: 45.0 }     # Ideal Load_CC: 5, was 4.9,4.75
    - { cccv: 2, Load_CC: 2.3, power: 45.0 }     # Ideal Load_CC: 2.5, was 2.4
    - { cccv: 3, Load_CC: 1.85, power: 45.0 }     # Ideal Load_CC: 2, was 1.9
    - { cccv: 4, Load_CC: 1.35, power: 45.0 }     # Ideal Load_CC: 1.5, was 1.4
    - { cccv: 255}

pdline: 1

dc_in: 1

commission:
  toggle: 1
  verbose: false
  settings:
    "/actuators/ALL":
      maxw: "100"
      pp: 100
      fadetime: 2000
      cv: 255
    "/sensors/ALL":
      sentype: "disable"
      eventlh: "default"
      eventhl: "default"
    "/network":
      lldp_enable: "false"


append_to_file: false

# cmd:
#   - "set_dim 0 100"
