 # Checks for version match
hold_load_time: 4  # How long the load stays active when on
http_server: "http://192.168.1.169:8081/firmware"
http_port: "8081"
remote_drivers: false

gateway_version: '2.16.1'
driver_version: '2.9.4'

mini_cp: 900
loxads:
  - toggle: 1
  - mini_cv: 12000
    mini_cc: 3000
    dim: 100
    Load_CR: 3.2
    power: 18.0
  - mini_cv: 24000
    mini_cc: 3000
    dim: 100
    Load_CR: 8.4 # Was / Should be 8, not 8.4. Doing this to speed it up.
    power: 58.0
  - mini_cv: 40000
    mini_cc: 2000
    dim: 100
    Load_CR: 22
    power: 65.0
  - mini_cv: 48000    # Mini Node Voltage Setting
    mini_cc: 2000     # Mini Node Current Setting
    dim: 100
    Load_CR: 28            # Load Machine Setting
    power: 67.0       # Power threshold

dexfacto_load_off_state: # x in there since toggle feature hasn't been implemented yet. Remove x to enable
  toggle: 0
  Load_CC: 0.050  # Sets the load machine to a given value instead of toggling off

rgbw: [4278190080, 16711680, 65280, 255, 4294967295] # [red,green,blue,white,all]
sensor1: true
pdline: true
firmware_upgrade: false
append_to_file: true

# Commission Settings
commission:
  toggle: 1
  settings:
    "/drivers/0/actuator":
      pwm_mode: "ALL_OFF"
      cc: 1000
      cv: 40000
      cp: 900
      cluster: "group1"

    "/drivers/0/wallswitch":
      cluster: "group1"

    "/drivers/0/sensor":
      cluster: "group1"
