{
  "cxode_version": "2out v Dec  9 2024 15:33:50", # Checks for version match
  "hold_load_time": 4, # How long the load stays active when on
  "http_server": "http://192.168.1.140:8081/firmware", 
  "http_port": "8081",
  "remote_drivers": false,
  "mini_cp": 900,
  "mini_cv": 40000,
  "mini_cc": 2000,
  "dim": 100,

  "loxads": [
    { "mini_cv": 12000, "mini_cc": 3000, "CR": 3.2, "power": 18.0 },
    { "mini_cv": 24000, "mini_cc": 3000, "CR": 8, "power": 58.0 },
    { "mini_cv": 40000, "mini_cc": 2000, "CR": 22, "power": 65.0 },
    { "mini_cv": 48000, "mini_cc": 2000, "CR": 23, "power": 67.0 }
  ],
  "dexfacto_load_off_state": {"toggle": 0, "CC": 0.050}, # Sets the load machine to a given value instead of toggling off. Make sure to set this low.

  "rxgbw": [4278190080,16711680,65280,255,4294967295],
  "sensor1": false,
  "pdline": false,
  "firmware_upgrade": false,
  "append_to_file": false,

  # Commission Settings
  commission:
    toggle: 1
    settings:
      - resource: "/drivers/0/actuator"
        key: "cc"
        value: 2000
      - resource: "/drivers/0/actuator"
        key: "cv"
        value: 40000
      - resource: "/drivers/0/actuator"
        key: "cp"
        value: 900
}
