{
  "subnet": "192.168.1.255",
  "cxode_version": "2out v Sep 26 2024 13:21:07",
  "cccv": 10,
  "hold_load_time": 10,
  "maxw": 620,
  "battery_backup_loads": 
  {
    "Low Load": { 
      "CV": 39, 
      "dim": 0, 
      "power":7 
      }, 

      "High Load": { 
        "CV": 40, 
        "dim": 100, 
        "power":40 
    }

},
  "await_time": 7,
  "await_key": "down",
  "maxw_commission": 100,
  "append_to_file": true,
  "cmd": ["set_dim 3 100"]
}
