code_version: "2out v Jun  5 2025 09:30:32"
update_db: 1

trigger_1_test: 1
chance_to_test_trigger_1: 100.0
number_of_trigger_1_attempts: 1.0
seconds_to_wait_for_restart: 8.0

maxw: 713
hold_load_time": 2 # Put comment here explaining this.

loads:
  toggle: 1
  test_steps:
  - { "cccv": 1, "CC": 3.3, "dim": 100, "power": 36.0 }
  - { "cccv": 2, "CC": 2.5, "dim": 100, "power": 56.0 }
  - { "cccv": 3, "CC": 2.0, "dim": 100, "power": 66.0 }
  - { "cccv": 4, "CC": 1.5, "dim": 100, "power": 66.0 }
  - { cccv: 4, CC: 1.5, dim: 0, below_power: 0.05, time_before_load_on: 3.0 }
  - { "cccv": 255, "dim": 100 }

sensor1: 1
pdline: 1

rs485: 1

commission:
  toggle: 1
  settings:
    "/actuators/ALL":
      cccv: "255"
      maxw: "100"
      pp: 100

append_to_file: true
