 # Checks for version match
hold_load_time: 4  # How long the load stays active when on
http_server: "http://192.168.1.51:8080/firmware"
http_port: "8080"
remote_drivers: false

gaxteway_version: '2.25.0'
dxiver_version: '2.16.0'

mini_cp: 900
loads:
  toggle: 1
  test_steps:
  - { mini_cv: 12000, mini_cc: 3000, dim: 100, CR: 3.2, power: 18.0, } 
  - { mini_cv: 24000, mini_cc: 3000, dim: 100, CR: 8.4, power: 58.0 } # Was / Should be 8, not 8.4. Doing this to speed it up.
  - { mini_cv: 40000, mini_cc: 2000, dim: 100, CR: 22, power: 65.0, } 
  - { mini_cv: 48000, mini_cc: 2000, dim: 100, CR: 28, power: 67.0 }

dexfacto_load_off_state: # x in there since toggle feature hasn't been implemented yet. Remove x to enable
  toggle: 0
  CC: 0.050  # Sets the load machine to a given value instead of toggling off

rxgbw: [4278190080, 16711680, 65280, 255, 4294967295] # [red,green,blue,white,all]
sensor1: 1
pdline: 1
firmware_upgrade: 0

# Commission Settings
commission:
  toggle: 1
  settings:
    "/drivers/0/actuator":
      pwm_mode: "ALL_OFF"
      cc: 2000
      cv: 40000
      cp: 900
      cluster: "group1"
    "/drivers/0/wallswitch":
      cluster: "group1"
    "/drivers/0/sensor":
      cluster: "group1"

append_to_file: true